CVbase/CVbase/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path(r'^jet/', include('jet.urls', 'jet')),
    path(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path("administracao/", admin.site.urls),
    # path("administracao/", include("users.urls")),
    path("", include("vagas.urls")),
]

users/urls.py
from django.urls import path

from .views import users_login, dashboard

from django.views.generic.base import RedirectView


urlpatterns = [
    path("", RedirectView.as_view(url='login?next=user', permanent=False), name='index')
]

vagas/urls.py
from django.urls import path

from .views import vagas_list, index, developer_page, ux_designer_page, marketing_page, project_manager_page, designer_page, candidatura_page

urlpatterns = [
    path("", index, name="index"),
    path("carreiras", vagas_list),
    path("carreiras/developer", developer_page),
    path("carreiras/ux-designer", ux_designer_page),
    path("carreiras/marketing", marketing_page),
    path("carreiras/project-manager", project_manager_page),
    path("carreiras/designer", designer_page),
    path("carreiras/candidatar/", candidatura_page)
]

users/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models

from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, max_length=255)
    name = models.CharField(max_length=255)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["name"]

    objects = UserManager()

    def __str__(self):
        return self.email

vagas/models.py
from django.db import models


class Vaga(models.Model):
    titulo = models.CharField(max_length=30)
    descricao = models.TextField()

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"[{self.titulo}] {self.descricao[:42]}..."

    class Meta:
        verbose_name = "vaga"
        verbose_name_plural = "vagas"
        ordering = ["-created"]


class Requisito(models.Model):
    vaga = models.ForeignKey("Vaga", on_delete=models.CASCADE)
    descricao = models.CharField(max_length=255)
    obrigatorio = models.BooleanField(default=True)

    def __str__(self):
        return f"[{self.vaga.titulo}] {self.descricao}"


class Beneficio(models.Model):
    vaga = models.ForeignKey("Vaga", on_delete=models.CASCADE)
    descricao = models.CharField(max_length=255)

    def __str__(self):
        return f"[{self.vaga.titulo}] {self.descricao}"


class Candidatura(models.Model):
    DEVELOP = 'DEVELOP'
    GERENTE_PROJETO = 'GERENTE_PROJETO'
    MARKETING = 'MARKETING'
    UXDESIGNER = 'UXDESIGNER'
    DESIGNER = 'DESIGNER'
    VAGA_CHOICES = (
        (DEVELOP, 'Develop'),
        (GERENTE_PROJETO, 'GerenteProjeto'),
        (MARKETING, 'Marketing'),
        (UXDESIGNER, 'UXDesigner'),
        (DESIGNER, 'Designer'),
    )

    vaga = models.CharField(choices=VAGA_CHOICES, max_length=100, default=DEVELOP)
    nome = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    telefone = models.CharField(max_length=255)
    experiencia_profissional = models.TextField(max_length=500)
    experiencia_academica = models.TextField(max_length=500)
    motivacao = models.TextField(max_length=500)

    def __str__(self):
        return f"[{self.nome}] {self.email}"

vagas/forms.py
from django import forms
from .models import Candidatura

class RegisterCandidatura(forms.ModelForm):

    class Meta:
        model = Candidatura
        fields = ('nome', 'email','telefone', 'experiencia_profissional', 'experiencia_academica', 'motivacao')

users/views.py
from django.shortcuts import render

# Create your views here.

vagas/views.py
from django.shortcuts import render

from .forms import RegisterCandidatura
from .models import Candidatura

# principal
def vagas_list(request):
    return render(request, "vagas/vaga_list.html")

def index(request):
    return render(request, "pages/index.html")

def candidatura(request):
    pass

# vagas
def developer_page(request):
    return render(request, "vagas/developer_page.html")

def designer_page(request):
    return render(request, "vagas/designer_page.html")

def ux_designer_page(request):
    return render(request, "vagas/ux_designer_page.html")

def marketing_page(request):
    return render(request, "vagas/marketing_page.html")

def project_manager_page(request):
    return render(request, "vagas/project_manager_page.html")

# candidatura
def candidatura_page(request):
    if request.method == 'POST':
        print("Entrou 1")

        form = RegisterCandidatura(request.POST)
    
        print("Validando form")
        if form.is_valid():
            print("Form válido 2")
            
            candidatura = form.save(commit=False)

            print(candidatura)

            candidatura.vaga = request.GET.get('vaga')
            candidatura.nome = request.POST['nome'] + " " + request.POST['sobrenome']
            candidatura.email = request.POST['email']
            candidatura.telefone = request.POST['telefone']
            candidatura.experiencia_profissional = request.POST['experiencia_profissional']
            candidatura.experiencia_academica = request.POST['experiencia_academica']
            candidatura.motivacao = request.POST['motivacao']
            
            print("Paasou daqui, já pode comemorar 3")

            candidatura.save()
            
            print("Salvo com a força do ódio 4")

            return render(request, "pages/sucesso.html")
        else:
            form = RegisterCandidatura()
        
    return render(request, "pages/candidatura_vaga.html")

templates/core/_footer.html
{% load static %}

<footer role="banner">
  <div class="container">
    <div class="final-footer text-center">
      <div class="col-xs-12">
        <img style="-webkit-filter: grayscale(100%);" width="150px" src="{% static 'images/pyrocode-logo.png' %}" alt="">
      </div>
      <div class="col-xs-12">
        <p>
          © <span id="footer-year">2019</span> Pyrocode Software -
        </p>
        <p>Entre em contato conosco em: <a
            href="mailto:contact.pyrocode@gmail.com"><u>contact.pyrocode@gmail.com</u></a></p>
      </div>
    </div>
  </div>
</footer>

templates/core/_navbar.html
{% load static %}
<nav class="navbar fixed-top navbar-expand-lg navbar-dark mybg-dark navbar-shrink">
  <div class="container-fluid">
    <a class="navbar-brand" href="javascript:void(0)">
      <h3 class="my-heading">
        <div class="col-xs-12">
          <img style="-webkit-filter: grayscale(100%);" width="150px" src="{% static 'images/pyrocode-logo.png' %}" alt="">
        </div>
      </h3>
    </a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
      data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="fa fa-bars mfa-white"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="text nav-link" href="/#home">Home</a>
        </li>
        <!-- TODO: Verificar parametro da URL e omitir links desnecessários -->
        <!-- % if false % -->
        <li class="nav-item">
          <a class="text nav-link" href="/#sobre">Sobre</a>
        </li>
        <li class="nav-item">
          <a class="text nav-link" href="/#equipe">Equipe</a>
        </li>
        <li class="nav-item">
          <a class="text nav-link" href="/carreiras">Vagas</a>
        </li>

        <li class="nav-item">
          <a style="display: inline-block;
            padding: 8px 20px;
            /*width: 128px;*/
            font-size: 14px;
            background: rgb(147, 131, 161);
            border: 1px solid#6F00E0;
            color: #ffffff;
            text-align: center;
            text-transform: uppercase;
            text-decoration: none;
            border-radius: 3px;
            cursor:pointer;
            box-shadow: 0px 0px 10px 0px #00000059;" href="/administracao/" class="btn-explore">Administrativo</a>
        </li>
        <!-- % endif % -->
      </ul>

    </div>

  </div>
</nav>

templates/core/template.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
	<title>CVB{ase}</title>
	<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="icon" href="{% static 'images/icons/favicon.ico' %}" />

  {% block style %}
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />
    <link rel="stylesheet" href="{% static 'css/careers.css' %}" />

    <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">  
	{% endblock %}
</head>

<body class="center">
  {% block navbar %}
    {% include "core/_navbar.html" %}
  {% endblock %}

  <main>
    {% block content %}{% endblock %}
  </main>

  {% block footer %}
    {% include "core/_footer.html" %}
  {% endblock %}

  {% block script %}
    <script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
    <script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
    <script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
  {% endblock %}
</body>

</html>

templates/pages/candidatura_vaga.html
{% extends "core/template.html" %}
{% load static %} 

{% block content %}
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<style>
/* body{ 
    margin-top:40px; 
} */
textarea, input {
    outline: #ccc;
    border: 1px solid #888; 
}

.setup-content {
    margin-top: 5%;  
    margin-left: 20%;
}
.nextBtn{
    font-size: 12px;
}
.stepwizard-step p {
    margin-top: 10px;
}

.stepwizard-row {
    display: table-row;
}

.stepwizard {
    display: table;
    width: 90%;
    position: relative;
}

.stepwizard-step button[disabled] {
    opacity: 1 !important;
    filter: alpha(opacity=100) !important;
}

.stepwizard-row:before {
    top: 14px;
    bottom: 0;
    position: absolute;
    content: " ";
    width: 100%;
    height: 1px;
    background-color: #ccc;
    z-order: 0;

}

.stepwizard-step {
    display: table-cell;
    text-align: center;
    position: relative;
}

.btn-circle {
    width: 30px;
    height: 30px;
    text-align: center;
    padding: 6px 0;
    font-size: 12px;
    line-height: 1.428571429;
    border-radius: 15px;
}

input.form-control, textarea.form-control {
    border-radius: 2rem;
    box-shadow: none;
    -webkit-box-shadow: 1px solid black;
    border-bottom: 2px solid #ccc;
    border-top: 2px solid #ccc;
    border-left: 2px solid #ccc;
    border-right: 2px solid #ccc;
    margin-bottom: 20px;
}
.form-div{
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 20px;
}
textarea {
  width: 300px;
  height: 150px;
}

</style>

<section style="background-image: url('{% static 'images/vaga-bg.jpg' %}'); background-position: 100px 5px;" class="intro">
  <header class="container">
    <div class="headline">
      <h1 style="color: rgb(87, 49, 87); text-shadow: gray 1px 1px 0;">Você está à um passo...</h1>
      <h3 style="color: rgb(87, 49, 87); text-shadow: gray 1px 1px 0;">De fazer parte de nosso time</h3>
    </div>
  </header>
</section>

<section class="career">
  <div class="container">
    <div class="open-roles-item">
      <div class="cta-career">
        
        <div class="container">
            <div class="stepwizard">
                <div class="stepwizard-row setup-panel">
                    <div class="stepwizard-step">
                        <a style="background-color: #8800E3; color: white" href="#step-1" type="button" class="btn btn-primary btn-circle">1</a>
                        <p>Sobre você</p>
                    </div>
                    <div class="stepwizard-step">
                        <a style="background-color: #8800E3; color: white"href="#step-2" type="button" class="btn btn-default btn-circle" disabled="disabled">2</a>
                        <p>Informações de contato</p>
                    </div>
                    <div class="stepwizard-step">
                        <a style="background-color: #8800E3; color: white" href="#step-3" type="button" class="btn btn-default btn-circle" disabled="disabled">3</a>
                        <p>Informações profissionais</p>
                    </div>
                </div>
            </div>
            <form method="POST" action="" role="form">
                {% csrf_token %}
                <div class="row setup-content" id="step-1">
                    <div class="form-div col-xs-12">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="control-label">Nome</label>
                                <input maxlength="100" type="text" required="required" class="form-control" name="nome" placeholder="Coloca aqui seu nome"  />
                            </div>
                            <div class="form-group">
                                <label class="control-label">Sobrenome</label>
                                <input maxlength="100" type="text" required="required" class="form-control" name="sobrenome" placeholder="Agora o sobrenome" />
                            </div>
                            <button class="btn btn-primary nextBtn btn-lg pull-right" type="button" >Próximo</button>
                        </div>
                    </div>
                </div>
                <div class="row setup-content" id="step-2">
                    <div class="form-div col-xs-12">
                        <div class="col-md-12">
                            <br>
                            <div class="form-group">
                                <label class="control-label">E-mail</label>
                                <input maxlength="200" type="email" required="required" class="form-control" name="email" placeholder="Informe seu email" />
                            </div>
                            <div class="form-group">
                                <label class="control-label">Telefone</label>
                                <input maxlength="200" type="text" required="required" class="form-control" name="telefone" placeholder="E um telefone para contato"  />
                            </div>
                            <button class="btn btn-primary nextBtn btn-lg pull-right" type="button" >Próximo</button>
                        </div>
                    </div>
                </div>
                <div class="row setup-content" id="step-3">
                    <div class="form-div col-xs-12">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="control-label">Experiência Profissional</label>
                                <textarea class="form-control" placeholder="Aqui você vai nos contar suas experiências profissionais" name="experiencia_profissional" cols="40" rows="10" maxlength="500" required id="id_experiencia_profissional"></textarea>
                            </div>
                            <div class="form-group">
                                <label class="control-label">Experiência acadêmica</label>
                                <textarea class="form-control" placeholder="Agora nos fale sobre sua experiência acadêmica" name="experiencia_academica" cols="40" rows="10" maxlength="500" required id="id_experiencia_academica"></textarea>
                            </div>
                            <div class="form-group">
                                <label class="control-label">Motivação</label>
                                
                                <textarea class="form-control" placeholder="Essa é a última! Aqui você vai falar quais são suas motivações em querar trabalhar com a gente" name="motivacao" cols="40" rows="10" maxlength="500" required id="id_motivacao"></textarea>
                            </div>
                            <button style="background-color: #8800E3; border-color: #8800E2; color: white" class="btn btn-sm pull-right" type="submit">Enviar!</button>
                        </div>
                    </div>
                </div>
            </form>
            </div>
        
      </div>
    </div>
  </div>
</section>
<script>
$(document).ready(function () {

var navListItems = $('div.setup-panel div a'),
        allWells = $('.setup-content'),
        allNextBtn = $('.nextBtn');

allWells.hide();

navListItems.click(function (e) {
    e.preventDefault();
    var $target = $($(this).attr('href')),
            $item = $(this);

    if (!$item.hasClass('disabled')) {
        navListItems.removeClass('btn-primary').addClass('btn-default');
        $item.addClass('btn-primary');
        allWells.hide();
        $target.show();
        $target.find('input:eq(0)').focus();
    }
});

allNextBtn.click(function(){
    var curStep = $(this).closest(".setup-content"),
        curStepBtn = curStep.attr("id"),
        nextStepWizard = $('div.setup-panel div a[href="#' + curStepBtn + '"]').parent().next().children("a"),
        curInputs = curStep.find("input[type='text'],input[type='url']"),
        isValid = true;

    $(".form-group").removeClass("has-error");
    for(var i=0; i<curInputs.length; i++){
        if (!curInputs[i].validity.valid){
            isValid = false;
            $(curInputs[i]).closest(".form-group").addClass("has-error");
        }
    }

    if (isValid)
        nextStepWizard.removeAttr('disabled').trigger('click');
});

$('div.setup-panel div a.btn-primary').trigger('click');
});
</script>
{% endblock %}

templates/pages/index.html
{% load static %}   

  {% block style %}
  <link rel="stylesheet" href="{% static 'css/4.0.0/bootstrap.min.css' %}" id="bootstrap-css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/4.7.0/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/3.7.0/animate.css' %}">
  <link rel="stylesheet" href="{% static 'css/index.css' %}" />
  {% endblock %}

  <header class="bg" id="home">
    <div class="overlay"></div>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark mybg-dark navbar-shrink">
      <div class="container-fluid">
        <a class="navbar-brand" href="javascript:void(0)">
          <h3 class="my-heading">
            <div class="col-xs-12">
              <img style="-webkit-filter: grayscale(100%);" width="150px" src="{% static 'images/pyrocode-logo.png' %}" alt="">
            </div>
          </h3>
        </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
          data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
          aria-label="Toggle navigation">
          <span class="fa fa-bars mfa-white"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="text nav-link" href="#home">Home</a>
            </li>
            <li class="nav-item">
              <a class="text nav-link" href="#sobre">Sobre</a>
            </li>
            <li class="nav-item">
              <a class="text nav-link" href="#equipe">Equipe</a>
            </li>
            <li class="nav-item">
              <a class="text nav-link" href="/carreiras">Vagas</a>
            </li>
            <li class="nav-item">
              <a href="/administracao/" class="btn-explore">Administrativo</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="tophead">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-7 ">
            <h2 class="wow fadeInLeft" data-wow-duration="1.5s"
              style="visibility: visible; animation-duration: 1.5s; animation-name: fadeInLeft;">
              Crie de forma inteligente, aventure-se além.
            </h2>
            <h1 class="subtitle-main wow fadeInUp" data-wow-duration="1.1s"
              style="visibility: visible; animation-duration: 1.1s; animation-name: fadeInUp;">
              Na Pyrocode, estabelecemos parcerias de longo prazo para desenvolver produtos digitais e inovadores para
              sua empresa.
            </h1>
          </div>
        </div>
      </div>
    </div>
    <div class="sesgoabajo"></div>
  </header>

  <main>
    <section class="overview-wrap" id="sobre">
      <div class="container">
        <div class="contenedor">
          <h2 class="title-overview wow fadeInUp" style="visibility: visible; animation-name: fadeInUp;">Sobre</h2>
          <p class="subtitle-overview wow fadeInUp" style="visibility: visible; animation-name: fadeInUp;">
            Pyrocode é uma empresa de software focada em projetos web. Gostamos de trabalhar com ferramentas Python e
            JavaScript, mas temos uma mente aberta para experimentar e brincar com outras linguagens e ferramentas.
            Django e Vue são nossas especialidades e adoramos trabalhar com APIs.
          </p>

          <p class="subtitle-overview wow fadeInUp" style="visibility: visible; animation-name: fadeInUp;">
            <b>Algumas tecnologias com as quais trabalhamos:</b>
          </p>
          <div class="row">

            <div class="col-md-6 col-lg-3 wow bounceInUp" data-wow-duration="1.4s"
              style="visibility: visible; animation-duration: 1.4s; animation-name: bounceInUp;">
              <div class="overview-box mx-auto">
                <img width="50%" src="{% static 'images//technologies/django.png' %}">
                <h5>Django</h5>
                <p class=" mb-0">um framework para aplicações web, de código aberto e gratuito, escrito em Python.!</p>
              </div>
            </div>
            <div class="col-md-6 col-lg-3 wow bounceInUp" data-wow-duration="1.4s"
              style="visibility: visible; animation-duration: 1.4s; animation-name: bounceInUp;">
              <div class="overview-box mx-auto">
                <img width="20%" src="{% static 'images/technologies/vue.png' %}">
                <h5>Vue</h5>
                <p class=" mb-0">framework JavaScript de código aberto, utilizando para construir interfaces e
                  aplicações de página unica.</p>
              </div>
            </div>
            <div class="col-md-6 col-lg-3 wow bounceInUp" data-wow-duration="1.4s"
              style="visibility: visible; animation-duration: 1.4s; animation-name: bounceInUp;">
              <div class="overview-box mx-auto">
                <img width="65%" src="{% static 'images/technologies/python.svg' %}">
                <h5>Python</h5>
                <p class=" mb-0">é uma linguagem de programação de alto nível, orientada a objetos, funcional, de
                  tipagem dinâmica e forte.</p>
              </div>
            </div>
            <div class="col-md-6 col-lg-3 wow bounceInUp" data-wow-duration="1.4s"
              style="visibility: visible; animation-duration: 1.4s; animation-name: bounceInUp;">
              <div class="overview-box mx-auto">
                <img width="33%" src="{% static 'images/technologies/nodejs.png' %}">
                <h5>Node</h5>
                <p class=" mb-0">é um ambiente de tempo de execução JavaScript de plataforma aberta, que executa o código JS fora de um navegador.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section class="galeria">
      <div class="sesgoarriba"></div>
      <div class="imagenes">
        <img
          src="{% static 'images/index-image-02.jpeg' %}"
          alt="" class="img-fluid">
        <div class="enmica">
          <div></div>
        </div>
      </div>
      <div class="sesgoabajo"></div>
    </section>

    <!--Our Team-->
    <section class="our-team" id="equipe">
      <div class="container">
        <h2 class="title-our-team wow fadeInUp" style="visibility: visible; animation-name: fadeInUp;">Nossa Equipe</h2>
        <p class="subtitle-our-team wow fadeInUp" style="visibility: visible; animation-name: fadeInUp;">Saiba mais
          sobre nós</p>
        <p class="subtitle-our-team wow fadeInUp" style="visibility: visible; animation-name: fadeInUp;">
          Somos especialistas em software e adoramos trabalhar com o Django, Vue, Python e as novas ferramentas
          disponíveis. Aderimos aos princípios ágeis, como Scrum. Então relaxe, seu software está em boas mãos porque
          sabemos que "Bonito é melhor que feio" e "Simples é melhor que complexo".
        </p>

        <ul class="row">
          <li class="col-12 col-md-6 col-lg-3 wow fadeInLeft" data-wow-duration="1.4s"
            style="visibility: visible; animation-duration: 1.4s; animation-name: fadeInLeft;">
            <div class="mycard-block equal-hight">
              <figure><img src="{% static 'images/team/02-rogerio.jpg' %}" class="img-fluid" alt=""></figure>
              <h3><a href="javascript:void(0)">Rogério Araújo</a></h3>
              <p>Desenvolvedor</p>
            </div>
          </li>
          <li class="col-12 col-md-6 col-lg-3 wow fadeInLeft" data-wow-duration="1.4s"
            style="visibility: visible; animation-duration: 1.4s; animation-name: fadeInLeft;">
            <div class="mycard-block equal-hight">
              <figure><img src="{% static 'images/team/01-fernanda.jpg' %}" class="img-fluid" alt=""></figure>
              <h3><a href="javascript:void(0)">Fernanda Vieira</a></h3>
              <p>Desenvolvedora mais linda dessa empresa</p>
            </div>
          </li>
          <li class="col-12 col-md-6 col-lg-3 wow fadeInLeft" data-wow-duration="1.4s"
            style="visibility: visible; animation-duration: 1.4s; animation-name: fadeInLeft;">
            <div class="mycard-block equal-hight">
              <figure><img src="{% static 'images/team/03-junio.jpg' %}" class="img-fluid" alt=""></figure>
              <h3><a href="javascript:void(0)">Junio Matias</a></h3>
              <p>UX Design</p>
            </div>
          </li>
          <li class="col-12 col-md-6 col-lg-3 wow fadeInLeft" data-wow-duration="1.4s"
            style="visibility: visible; animation-duration: 1.4s; animation-name: fadeInLeft;">
            <div class="mycard-block equal-hight">
              <figure><img src="{% static 'images/team/04-aguirre.jpg' %}" class="img-fluid" alt=""></figure>
              <h3><a href="javascript:void(0)">Aguirre Sabino</a></h3>
              <p>Desenvolvedor</p>
            </div>
          </li>
        </ul>
      </div>
    </section>
  </main>
  <footer class="footer bg-dark">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center  my-auto ">
          <p class="mb-4 mb-lg-0">© Pyrocode 2019. All Rights Reserved.</p>
        </div>
      </div>
    </div>
  </footer>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"></script>
  <script>
    new WOW().init();

  </script>
  <script>
    $(window).on("scroll", function () {
      if ($(this).scrollTop() > 10) {
        $("nav.navbar").addClass("mybg-dark");
        $("nav.navbar").addClass("navbar-shrink");

      } else {
        $("nav.navbar").removeClass("mybg-dark");
        $("nav.navbar").removeClass("navbar-shrink");

      }

    });

  </script>

templates/pages/sucesso.html
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>

<section class="success">
    <div class="container">
        <div class="row text-center">
            <br><br>
            <div class="col-sm-6 col-sm-offset-3">
            <br><br> <h2 style="color:#8800E3">Tudo certo!</h2>
            <img width="150"src="https://cdn.dribbble.com/users/129972/screenshots/3964116/75_smile.gif">
            <h3>Aguarde que logo entraremos em contato.</h3>
            <p style="font-size:20px;color:#8800E3;">Obrigado pelo interesse em se junta a nossa equipe!</p>
            <a href="/" style="background-color: #8800E3;background-border: #8800E3; color: white" class="btn">     Voltar para o inicio      </a>
            <br><br>
            </div>
        </div>
    </div>
</section>